# Generated by Django 2.2.19 on 2021-04-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210327_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
